### ISSUE TITLE
Failed to install Swift 5.8 on Ubuntu22.04 aarch64

### ISSUE THREAD

**Issue by Kyle-Ye** [stevapple/swiftbox#4]
The download link now is wrong and will get a 404 Not Found response
```
https://download.swift.org/swift-5.8-release/ubuntu2204/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04-aarch64.tar.gz
```

The correct link is the following (According to https://www.swift.org/download/)
```
https://download.swift.org/swift-5.8-release/ubuntu2204-aarch64/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04-aarch64.tar.gz
```

**Comment by stevapple** [comment]
Thanks for reporting, @Kyle-Ye! Going to provide a fix soon.

**Comment by Kyle-Ye** [comment]
> Thanks for reporting, @Kyle-Ye! Going to provide a fix soon.

The `DOWNLOAD_URL` in [check-version](https://github.com/stevapple/swiftbox/blob/0809a71ce1fb5166a9004d0657e3582a1e7881ff/swiftbox.sh#L247) in correct and is wrong in [fetch-release](https://github.com/stevapple/swiftbox/blob/0809a71ce1fb5166a9004d0657e3582a1e7881ff/swiftbox.sh#L289)
